# Generated by Django 5.1.7 on 2025-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resource_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='arriving_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
