# Generated by Django 5.1.7 on 2025-04-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delivery_deliveryresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_forecast',
            field=models.JSONField(default=list),
        ),
    ]
